# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: gateway-dev
    image: isl-dsdc.ca.com:5000/apim-gateway/gateway-base/nightly
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ./docker/license.xml:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
#      - ./docker/delay.req.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/delay.req.bundle
      - ./src/test/resources/example-project-live/build/gateway/example-project-live.bundle:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/bundle/zipped.req.bundle
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      EXTRA_JAVA_ARGS: "-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
#       -Dcom.l7tech.server.config.mode=RUNTIME"